# Default values for cat-encyclopedia.

replicaCount: 1

image:
  repository: guidemetothemoon/cat-encyclopedia
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: addon-http-application-routing
  hosts:
    - host: cat-encyclopedia.<CLUSTER_SPECIFIC_DNS_ZONE>
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
